app.yaml.copy: added --workers flag to increase the number of workers (by default 1) Fix: if the same image is used by several products there was an exception (AttributeError: 'bool' object has no attribute 'strftime' in `file_utils.download_file`) server: initialization code moved from module's root into on_instance_start (handler of _ah/start GAE warmup request) to prevent multiple execution by several workers
Change-Id: I4f1898e1741aa078f172de649c02f40ff3d8bffb